---
title: "SVM - Week 1"
output: github_document
---

```{r loading required libraries and importing data, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)

library('kernlab')
library('RCurl')
library('ggplot2')
library('GGally')
library('mlr')

file <- try(getURL('https://d37djvu3ytnwxt.cloudfront.net/assets/courseware/v1/e39a3df780dacd5503df6a8322d72cd2/asset-v1:GTx+ISYE6501x+2T2017+type@asset+block/credit_card_data-headers.txt', ssl.verifyhost=FALSE, ssl.verifypeer=FALSE))

data <- read.csv(textConnection(file), header=T, sep = "\t")

head(data)

```

```{r, fig.height=10, fig.width=10, message=FALSE, warning=FALSE}

#Visualize high dimensional feature space 
data[,11] <- as.factor(data[,11])
GGally::ggpairs(data[, c(2:4,9:11)], aes(colour=R1))


```



```{r, echo=TRUE}

try(x <- as.matrix(data[ ,1:10]))
y <- data[ ,11]

model <- ksvm(y ~ x, type = "C-svc", kernal = "polydot", C=100, scaled = TRUE, cross = 3)

a <- colSums(data[model@SVindex,1:10]*model@coef[[1]])
cat('coefficients:',a,'\n')

a0 <- sum(a*data[1,1:10]) - model@b
cat('a0:',a0,'\n')

pred <- predict(model,data[,1:10])
# pred

cat('SVM accuracy:',sum(pred == data[,11]) / nrow(data),'\n')

cat('b:',b(model),'\n')
cat('error:',error(model),'\n')
kernelf(model)

```

```{r}
#Kernal comparison - pplinedot and tanhdot has the highest accuracy

kernals <- c('rbfdot','polydot','vanilladot','tanhdot','laplacedot','besseldot','anovadot','splinedot','stringdot')

for(kernal in kernals){
model <- ksvm(y ~ x, type = "C-svc", kernal = "polydot", C=100, scaled = TRUE, cross = 3)
pred <- predict(model,data[,1:10])
cat('\n',kernal,'pred: ', sum(pred == data[,11]) / nrow(data))
}
```




